name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Install Yarn
      #   run: npm install -g yarn

      - name: Install dependencies
        run: |
          npm install
          npm install --legacy-peer-deps

      - name: Lint code
        run: npm lint

      # - name: Run unit tests
      #   run: yarn test --watch=false --no-progress --browsers=ChromeNoSandboxHeadless

      # - name: Build project
      #   run: yarn build --configuration production

      # - name: Upload production build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: production-build
      #     path: dist/
