name: Build and Test Angular App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Set the Node.js version (adjust as needed)

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Angular CLI with Yarn
        run: yarn global add @angular/cli@latest

      - name: Install Dependencies
        run: yarn install

      - name: Build Angular Application
        run: ng build --configuration=production

      - name: Run Tests
        run: ng test --watch=false --no-progress --browsers=ChromeHeadless
